In [1]:
import numpy as np
import math as mt

In [6]:
def fac2(n: int):
    a = 1
    for i in range(n, 0, -2):
        a *= i
    return a

## Generate m

In [124]:
def generateA(m):
    n = m // 2
    A = np.zeros((n + 1, n + 1), dtype=np.int64)
    if m % 2 == 0:
        for i in range(0, n+1):
            for j in range(0, i+1):
                if (i%2) == (j%2):
                    # print(f'matrix i: {i}, j: {j}')
                    A[i][j] = mt.comb(i, j) * mt.comb(2*n - i, j) * fac2(i-j-1) * fac2(2*n-i-j-1)
    else:
        for i in range(0, n+1):
            for j in range(0, i+1):
                if (i%2) == (j%2):
                    # print(i, j, mt.comb(i, j) , 2*n+1-i, j)
                    A[i][j] = mt.comb(i, j) * mt.comb(2*n+1-i, j) * mt.factorial(j) * fac2(i-j-1) * fac2(2*n+1-i-j)
                else:
                    A[i][j] = mt.comb(i, j) * mt.comb(2*n+1-i, j) * mt.factorial(j) * fac2(i-j) * (2*n-i-j)
    return A

## Generate local polynomial under pinnings

In [125]:
def generateH(function: list):
    d = len(function)
    for i in range(0, d):
        for j in range(i, d):
            function_under_pinnings = np.array(function[i:j+1])
            complement = function[i:j+1]
            # a = []
            complement.reverse()
            complement = np.array(complement)
            # print(function_under_pinnings, complement)
            H = function_under_pinnings * complement
            l = len(H)-1
            if l == 0:
                continue
            h = H[:l//2+1]
            # print(f'H, l: {l}, h: {h}, H: {H}')
            yield (h, l)
            
            
        

## Choose your local polynomial here

In [132]:
F = [1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0]

In [133]:
for (h,m) in generateH(F):
    A = generateA(m)
    
    x = np.linalg.solve(A, h)
    print(f'm: {m} \n h: {h} \n A: \n{A} \n x: {x}')
    if (x<0).any():
        print('error!')
        break
    

m: 1 
 h: [1] 
 A: 
[[1]] 
 x: [1.]
m: 2 
 h: [1 1] 
 A: 
[[1 0]
 [0 1]] 
 x: [1. 1.]
m: 3 
 h: [1 1] 
 A: 
[[3 0]
 [1 2]] 
 x: [0.33333333 0.33333333]
m: 4 
 h: [1 1 1] 
 A: 
[[3 0 0]
 [0 3 0]
 [1 0 1]] 
 x: [0.33333333 0.33333333 0.66666667]
m: 5 
 h: [1 1 1] 
 A: 
[[15  0  0]
 [ 3 12  0]
 [ 3  6  6]] 
 x: [0.06666667 0.06666667 0.06666667]
m: 6 
 h: [1 1 1 1] 
 A: 
[[15  0  0  0]
 [ 0 15  0  0]
 [ 3  0  6  0]
 [ 0  9  0  1]] 
 x: [0.06666667 0.06666667 0.13333333 0.4       ]
m: 7 
 h: [1 1 1 1] 
 A: 
[[105   0   0   0]
 [  5  90   0   0]
 [ 15  30  60   0]
 [  9  36  36  24]] 
 x: [0.00952381 0.01058201 0.00899471 0.00873016]
m: 8 
 h: [1 1 1 1 1] 
 A: 
[[105   0   0   0   0]
 [  0 105   0   0   0]
 [ 15   0  45   0   0]
 [  0  45   0  10   0]
 [  9   0  36   0   1]] 
 x: [0.00952381 0.00952381 0.01904762 0.05714286 0.22857143]
m: 9 
 h: [0 1 1 1 1] 
 A: 
[[945   0   0   0   0]
 [  7 840   0   0   0]
 [105  70 630   0   0]
 [ 15 270 270 360   0]
 [ 45 180 360 240 120]] 
 x: [0.     